version: "3.9"

services:

  daruru-db:
    image: mysql:8
    container_name: daruru-db
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: Bunny2026$
      MYSQL_DATABASE: daruru_farm

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - darurufarms-network

  darurufarms-backend:
    image: 739030358103.dkr.ecr.ap-south-2.amazonaws.com/darurufarm-backend:latest

    container_name: darurufarms-backend

    restart: unless-stopped

    depends_on:
      - daruru-db

    environment:
      DB_HOST: daruru-db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: Bunny2026$
      DB_DATABASE: daruru_farm
      JWT_SECRET: super_secret_key_123
      PORT: 3000

    ports:
      - "3000:3000"

    networks:
      - darurufarms-network

  darurufarms-frontend:

    image: 739030358103.dkr.ecr.ap-south-2.amazonaws.com/darurufarm-frontend:latest

    container_name: darurufarms-frontend

    restart: unless-stopped

    depends_on:
      - darurufarms-backend

    ports:
      - "80:80"

    networks:
      - darurufarms-network

networks:
  darurufarms-network:

volumes:
  mysql_data:
