module.exports = [
  {
    date: '2026-07-01',
    activityType: 'Maintenance',
    notes: 'Cleared weeds and loose dirt around the plants. Removed dead leaves and plant debris. Checked overall plant health. Cleaned the field pathways.',
  },
  {
    date: '2026-07-02',
    activityType: 'Maintenance',
    notes: 'Adjusted and repaired damaged sections of the farm fence. Checked fence posts for stability. Removed weeds growing near the fence. Inspected the field boundary.',
  },
  {
    date: '2026-07-03',
    activityType: 'Irrigation',
    notes: 'Irrigated the plants. Checked the drip irrigation lines. Removed blocked emitters. Recorded water usage.',
  },
  {
    date: '2026-07-04',
    activityType: 'Fertilization',
    notes: 'Applied organic fertilizer around the plants. Removed weeds from the root zone. Checked soil moisture. Inspected plants for nutrient deficiency symptoms.',
  },
  {
    date: '2026-07-05',
    activityType: 'Other',
    notes: 'Conducted pest inspection. Checked leaves and young shoots for insect activity. Removed visibly damaged leaves. Recorded pest observations.',
  },
  {
    date: '2026-07-06',
    activityType: 'Pesticide Application',
    notes: 'Applied fungicide as a preventive treatment. Inspected leaves for fungal spots. Checked weather conditions before spraying. Cleaned spraying equipment after use.',
    pesticideName: 'Preventive fungicide',
    pesticideQuantity: 'As recommended',
    pesticideTime: 'Morning',
  },
  {
    date: '2026-07-07',
    activityType: 'Irrigation',
    notes: 'Irrigated the field. Checked water pressure in the drip system. Cleaned the water filter. Inspected plants for signs of water stress.',
  },
  {
    date: '2026-07-08',
    activityType: 'Maintenance',
    notes: 'Removed weeds between plant rows. Loosened compacted soil around selected plants. Cleaned the field pathways. Collected plant debris.',
  },
  {
    date: '2026-07-09',
    activityType: 'Pesticide Application',
    notes: 'Applied pesticide to affected areas. Inspected plants for insects. Recorded pesticide quantity used. Cleaned spraying equipment.',
    pesticideName: 'Pesticide (affected areas)',
    pesticideQuantity: 'Recorded on site',
    pesticideTime: 'Morning',
  },
  {
    date: '2026-07-10',
    activityType: 'Other',
    notes: 'Conducted disease inspection. Checked leaves for spots and discoloration. Marked plants showing symptoms. Updated the daily farm log.',
  },
  {
    date: '2026-07-11',
    activityType: 'Irrigation',
    notes: 'Irrigated the field. Checked soil moisture. Inspected drip pipes for leakage. Repaired a minor irrigation leak.',
  },
  {
    date: '2026-07-12',
    activityType: 'Fertilization',
    notes: 'Applied fertilizer. Distributed fertilizer evenly around plants. Removed weeds around fertilizer application areas. Recorded fertilizer usage.',
  },
  {
    date: '2026-07-13',
    activityType: 'Pruning',
    notes: 'Pruned damaged and dead branches. Removed diseased plant material. Collected and disposed of pruning waste. Inspected new growth.',
  },
  {
    date: '2026-07-14',
    activityType: 'Pesticide Application',
    notes: 'Conducted pest inspection. Checked fruits and leaves for insect damage. Applied neem-based treatment to affected areas. Recorded observations.',
    pesticideName: 'Neem-based treatment',
    pesticideQuantity: 'Spot application',
    pesticideTime: 'Morning',
  },
  {
    date: '2026-07-15',
    activityType: 'Irrigation',
    notes: 'Irrigated the field. Checked water tank level. Cleaned irrigation filters. Inspected plants for wilting.',
  },
  {
    date: '2026-07-16',
    activityType: 'Irrigation',
    notes: 'Heavy rainfall occurred. Irrigation was reduced due to sufficient rainfall. Checked field drainage. Removed standing water from low-lying areas.',
  },
  {
    date: '2026-07-17',
    activityType: 'Other',
    notes: 'Inspected plants after rainfall. Checked for fungal disease symptoms. Removed damaged leaves and fruits. Improved drainage around affected plants.',
  },
  {
    date: '2026-07-18',
    activityType: 'Pesticide Application',
    notes: 'Applied preventive fungicide. Inspected leaves and fruits. Recorded treatment details. Cleaned spraying equipment.',
    pesticideName: 'Preventive fungicide',
    pesticideQuantity: 'As recommended',
    pesticideTime: 'Morning',
  },
  {
    date: '2026-07-19',
    activityType: 'Maintenance',
    notes: 'Removed weeds from all major field rows. Cleaned the area around irrigation lines. Collected plant debris. Checked soil moisture.',
  },
  {
    date: '2026-07-20',
    activityType: 'Other',
    notes: 'Conducted detailed disease inspection. Identified a few plants showing leaf spots. Marked affected plants. Recorded disease observations.',
  },
  {
    date: '2026-07-21',
    activityType: 'Irrigation',
    notes: 'Irrigated the field. Checked drip emitters. Replaced two damaged emitters. Recorded irrigation usage.',
  },
  {
    date: '2026-07-22',
    activityType: 'Fertilization',
    notes: 'Applied fertilizer. Checked plant growth. Removed weeds around plants. Recorded fertilizer application.',
  },
  {
    date: '2026-07-23',
    activityType: 'Pesticide Application',
    notes: 'Conducted pest inspection. Checked young leaves and fruits. Applied pesticide to affected areas. Recorded pesticide quantity.',
    pesticideName: 'Pesticide (affected areas)',
    pesticideQuantity: 'Recorded on site',
    pesticideTime: 'Morning',
  },
  {
    date: '2026-07-24',
    activityType: 'Pruning',
    notes: 'Pruned excess and damaged branches. Removed dead plant material. Cleaned pruning tools. Inspected new shoots.',
  },
  {
    date: '2026-07-25',
    activityType: 'Irrigation',
    notes: 'Checked weather forecast. Inspected soil moisture. Reduced irrigation due to expected rainfall. Checked drainage channels.',
  },
  {
    date: '2026-07-26',
    activityType: 'Other',
    notes: 'Rainfall received during the day. Inspected field drainage. Checked plants for fungal symptoms. Removed waterlogged debris.',
  },
  {
    date: '2026-07-27',
    activityType: 'Pesticide Application',
    notes: 'Conducted post-rain disease inspection. Found minor fungal symptoms on several leaves. Applied recommended fungicide treatment. Recorded affected area.',
    pesticideName: 'Recommended fungicide',
    pesticideQuantity: 'Affected area only',
    pesticideTime: 'Morning',
  },
  {
    date: '2026-07-28',
    activityType: 'Irrigation',
    notes: 'Irrigated only dry sections of the field. Checked water distribution. Cleaned drip filters. Inspected plant health.',
  },
  {
    date: '2026-07-29',
    activityType: 'Other',
    notes: 'Conducted complete pest and disease inspection. Removed infected leaves. Checked fruit development. Updated farm observations.',
  },
  {
    date: '2026-07-30',
    activityType: 'Other',
    notes: 'Completed monthly field inspection. Reviewed irrigation and pesticide activities. Recorded plant growth observations. Cleaned the field and equipment. Prepared activities for the following month.',
  },
];
